// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function RequestContact(arg1) {
  return window['go']['main']['App']['RequestContact'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetCorrespondent(arg1) {
  return window['go']['main']['App']['SetCorrespondent'](arg1);
}

export function UpdateContacts() {
  return window['go']['main']['App']['UpdateContacts']();
}
