// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptConferenceInvitation(arg1) {
  return window['go']['main']['App']['AcceptConferenceInvitation'](arg1);
}

export function AcceptSubscription(arg1) {
  return window['go']['main']['App']['AcceptSubscription'](arg1);
}

export function CancelSubscription(arg1) {
  return window['go']['main']['App']['CancelSubscription'](arg1);
}

export function CreateConference(arg1) {
  return window['go']['main']['App']['CreateConference'](arg1);
}

export function DeclineConference(arg1, arg2) {
  return window['go']['main']['App']['DeclineConference'](arg1, arg2);
}

export function DeleteAccount() {
  return window['go']['main']['App']['DeleteAccount']();
}

export function DeleteConference(arg1) {
  return window['go']['main']['App']['DeleteConference'](arg1);
}

export function ExitConference(arg1) {
  return window['go']['main']['App']['ExitConference'](arg1);
}

export function GetArchive(arg1) {
  return window['go']['main']['App']['GetArchive'](arg1);
}

export function GetConferences() {
  return window['go']['main']['App']['GetConferences']();
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetCurrentShow() {
  return window['go']['main']['App']['GetCurrentShow']();
}

export function GetCurrentStatus() {
  return window['go']['main']['App']['GetCurrentStatus']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetMessagesConference(arg1) {
  return window['go']['main']['App']['GetMessagesConference'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ProbeContacts() {
  return window['go']['main']['App']['ProbeContacts']();
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function RejectSubscription(arg1) {
  return window['go']['main']['App']['RejectSubscription'](arg1);
}

export function RequestContact(arg1) {
  return window['go']['main']['App']['RequestContact'](arg1);
}

export function SendConferenceFileMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendConferenceFileMessage'](arg1, arg2, arg3);
}

export function SendConferenceMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendConferenceMessage'](arg1, arg2, arg3);
}

export function SendFileMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFileMessage'](arg1, arg2, arg3);
}

export function SendInvitation(arg1, arg2) {
  return window['go']['main']['App']['SendInvitation'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetStatus(arg1) {
  return window['go']['main']['App']['SetStatus'](arg1);
}

export function SetStatusMessage(arg1) {
  return window['go']['main']['App']['SetStatusMessage'](arg1);
}

export function UpdateContacts() {
  return window['go']['main']['App']['UpdateContacts']();
}
