// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AcceptSubscription(arg1:string):Promise<void>;

export function CancelSubscription(arg1:string):Promise<void>;

export function GetContacts():Promise<Array<string>>;

export function GetMessages(arg1:string):Promise<Array<models.Message>>;

export function RequestContact(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetCorrespondent(arg1:string):Promise<void>;

export function UpdateContacts():Promise<void>;
