// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptSubscription(arg1) {
  return window['go']['main']['App']['AcceptSubscription'](arg1);
}

export function CancelSubscription(arg1) {
  return window['go']['main']['App']['CancelSubscription'](arg1);
}

export function GetArchive(arg1) {
  return window['go']['main']['App']['GetArchive'](arg1);
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetMessagesConference(arg1) {
  return window['go']['main']['App']['GetMessagesConference'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function RequestContact(arg1) {
  return window['go']['main']['App']['RequestContact'](arg1);
}

export function SendConferenceMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendConferenceMessage'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetStatus(arg1) {
  return window['go']['main']['App']['SetStatus'](arg1);
}

export function UpdateContacts() {
  return window['go']['main']['App']['UpdateContacts']();
}
