// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AcceptConferenceInvitation(arg1:string):Promise<void>;

export function AcceptSubscription(arg1:string):Promise<void>;

export function CancelSubscription(arg1:string):Promise<void>;

export function CreateConference(arg1:string):Promise<void>;

export function DeclineConference(arg1:string,arg2:string):Promise<void>;

export function DeleteAccount():Promise<void>;

export function GetArchive(arg1:string):Promise<void>;

export function GetConferences():Promise<Array<{[key: string]: string}>>;

export function GetContacts():Promise<Array<string>>;

export function GetCurrentStatus():Promise<string>;

export function GetCurrentUser():Promise<string>;

export function GetMessages(arg1:string):Promise<Array<models.Message>>;

export function GetMessagesConference(arg1:string):Promise<Array<models.Message>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function ProbeContacts():Promise<void>;

export function Register(arg1:string,arg2:string):Promise<boolean>;

export function RejectSubscription(arg1:string):Promise<void>;

export function RequestContact(arg1:string):Promise<void>;

export function SendConferenceFileMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendConferenceMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendFileMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendInvitation(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetStatus(arg1:number):Promise<void>;

export function SetStatusMessage(arg1:string):Promise<void>;

export function UpdateContacts():Promise<void>;
