// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContacts():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SendMessage(arg1:string):Promise<void>;

export function SetCorrespondent(arg1:string):Promise<void>;

export function UpdateContacts():Promise<void>;
